#
# Makefile for the td lock driver.
#

# Object file lists.

obj-y := tddriver.o

tddriver-y := main.o
tddriver-y += tpmcmd.o
tddriver-y += util.o
tddriver-y += ipc.o
tddriver-y += sclock.o
tddriver-y += smbios.o

tddriver-objs := $(tddriver-y)

